name: Quick Data Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "literature/**"

jobs:
  quick-validation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # full history needed for git diff against origin/main
      - uses: prefix-dev/setup-pixi@v0.9.5
        with: { pixi-version: v0.67.1 }
      - name: validate new entries
        shell: pixi run bash -e {0}
        run: pixi run -e dev validate-new-input -- --base_ref origin/${{ github.base_ref }}
